### ISSUE TITLE
movies button

### ISSUE THREAD

**Issue by OmklthomAmara** [WebAhead7/MovieDb#3]
while i'm in the about page and trying to go back to movies page, the movies button stuck and doesn't work.

**Comment by Karyum** [comment]
![mo](https://user-images.githubusercontent.com/24195641/96838011-f4628000-144f-11eb-89e7-2a05f3117da2.PNG)

**Comment by nuwrss** [comment]
@OmklthomAmara 
hi i cant understand the issue 
i tried to enter the the about us page and return to the movies page all works fine

**Comment by ghost** [comment]
Maybe change the z-index attribute in the css file ?

**Comment by nuwrss** [comment]
issue solved
