### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/MovieDb#4]
https://github.com/WebAhead7/MovieDb/blob/main/src/home.js#L38

in case of a real error or response is not ok, this line of code will crash the website even if you have throw.

because the `errrooooor` variable does not exist.

also in the `.catch` you are only console logging the an error, in case of a real error then the website will be broken and the user has no idea what happened

**Comment by nuwrss** [comment]
done , we added alert to the catch
